### ISSUE TITLE
Wrong validation of  emails with $! chars

### ISSUE THREAD

**Issue by mrded** [manishsaraan/email-validator#23]
I found that `validator.validate('foo$!@bar.com')` returns `true`. It must be `false`.

    it("should be able to validate('foo$!@bar.com')", function() {
      expect(validator.validate('foo$!@bar.com')).toEqual(false);
    });

**Comment by manishsaraan** [comment]
@mrded can you submit a pr for this. Thanks

**Comment by shirayukikitsune** [comment]
According to the [RFC 3696](https://tools.ietf.org/html/rfc3696#page-5), it is allowed to use those characters in the local part of an e-mail address.
