### ISSUE TITLE
Rewrite tests, add CI, Coverage and create UMD for browser

### ISSUE THREAD

**Issue by manishsaraan** [manishsaraan/email-validator#24]
Hi @Sembiance . I am willing to rewrite tests for this library with mocha, and travis ci and create Universal Module Definition for consuming this module in browser. Just want to confirm if i can work as there is not changes made in this module since aug 2017. 
Thanks :).

**Comment by manishsaraan** [comment]
CC : @Sembiance  I have updated the tests. refer #25

**Comment by Sembiance** [comment]
So I don't have much time now a days to maintain this module.

Would you like to take it over? I could transfer the github repo to you and also make you the owner of the NPM package.

If so, shoot me an e-mail (robert@cosmicrealms.com) with what NPM username you want me to assign the the module to.
