### ISSUE TITLE
Breaking change in minor update

### ISSUE THREAD

**Issue by jsg2021** [manishsaraan/email-validator#26]
the arrow function raised the minimum node version to 4. This library previously functioned in older environments. This should be a semver major update. Could 1.2.x be unpublished and bumped to 2.0?

**Comment by manishsaraan** [comment]
Thanks @jsg2021 . will do it. Should i have to add min node version to 4.0 in package.json as well.

**Comment by jsg2021** [comment]
that’s not required, but would be nice

**Comment by manishsaraan** [comment]
Great thanks. Will publish v2.0 soon.

**Comment by manishsaraan** [comment]
version updated. Closing this issue.

**Comment by jsg2021** [comment]
Please unpublish 1.2.1 so that `^1.1.1` doesn't get the breaking change
