### ISSUE TITLE
Email is True?

### ISSUE THREAD

**Issue by mrpassiontea** [manishsaraan/email-validator#31]
I'm testing out some emails, for some reason the `validator.validate("beep+12093@gma.awic.com");`
is returning true for that email?

**Comment by juanstiza** [comment]
That is indeed a valid email address, see: [https://tools.ietf.org/html/rfc5233](url).

**Comment by eyedean** [comment]
@manishsaraan it might not be a bad idea to close some of these resolved/not-a-problem-anymore issues.

I was shopping for a simple Email Validation package in NPM, and when I found this one I was a little bit skeptical seeing it has 11 open issues.  However, digging a little bit deeper I found most of them are not exactly an issue. : )

Thanks.
