### ISSUE TITLE
Double hyphen issue

### ISSUE THREAD

**Issue by hermawan22** [manishsaraan/email-validator#32]
## How to reproduce
Try use email with double hyphen, for example : `test@test--1.com`

## Expected Result
`test@test--1.com` should be valid email

## Actual Result
`test@test--1.com` return as invalid email

**Comment by hermawan22** [comment]
#33 I created pull request for it.

**Comment by manishsaraan** [comment]
Merged. Thanks for contribution @hermawan22 ;
