### ISSUE TITLE
Does not validate firstname.middlename.lastname@gmail.com

### ISSUE THREAD

**Issue by eljaouharihamza** [manishsaraan/email-validator#41]
Hello,

This validator returns invalid for the "firstname.middlename.lastname@gmail.com" emails pattern like.

`			if(EmailValidator.validate(this.email)){
				alert("invalid");
			}else{
				alert("valid");
			}`

:)

Have a great day !

**Comment by eyedean** [comment]
@eljaouharihamza I just checked `firstname.middlename.lastname@gmail.com` and it's valid.

```js
var validator = require("email-validator");

res = validator.validate("firstname.middlename.lastname@gmail.com");
console.log({res});
``` 

It prints out `{res: true}`.

So the problem must be somewhere else in your code.

**Comment by eljaouharihamza** [comment]
Thank you :)
