### ISSUE TITLE
 reduce the size of index.js

### ISSUE THREAD

**Issue by ValeriyDyachenko** [manishsaraan/email-validator#50]
Please remove comments from index.js file and minify it.

**Comment by bradisbell** [comment]
@ValeriyDyachenko It's best to leave comments in the code.  Your bundler can handle this task.

**Comment by manishsaraan** [comment]
@ValeriyDyachenko This library is shipped as is without compiled because its a small one. I think @bradisbell is right, eventually bundler can handle this job.
