### ISSUE TITLE
Provide concise error messages

### ISSUE THREAD

**Issue by axelrindle** [manishsaraan/email-validator#52]
What about returning an error message to precisely indicate what is wrong with the given value instead of just returning `true` or `false`?

**Comment by manishsaraan** [comment]
@axelrindle Current behaviour of this library is verify if given email is valid or not. Could you give some example what response you expecting from the response

**Comment by axelrindle** [comment]
For example: If the email is too long, a message like the following could be returned:

```
The given email exceeds the maximum length of 256 characters!
```

Or just:

```
The given email is too long!
```
