### ISSUE TITLE
what is the maximum limit of requests per month?

### ISSUE THREAD

**Issue by rohan2734** [manishsaraan/email-validator#64]
what is the maximum limit of requests per month?

**Comment by jl-a** [comment]
This is a library for inclusion designed to be bundled as part of a larger webapp. There is no limit.

**Comment by houd1ni** [comment]
As @jl-a stated, there's no artificial limit.
I'd add that there would be no external API requests and the library would live inside of your hardware, and therefore only limited by its' capabilities. But I doubt that the lib can become a bottleneck if not explicitly run in large database loop or terribly written cyclic code.
