### ISSUE TITLE
How could we check if an email is personal email or company email?

### ISSUE THREAD

**Issue by chengtie** [manishsaraan/email-validator#70]
By "personal email", I mean `@google.com`, `@msn.com`, etc.

Could you suggest any open source library?

**Comment by pober** [comment]
You can use something like https://www.npmjs.com/package/free-email-domains or https://www.npmjs.com/package/email-providers I guess

**Comment by houd1ni** [comment]
@pober answer is perfect. Closing the issue and maybe make the feature as opt-in in future release. Thanks!
