### ISSUE TITLE
Maintenance. 

### ISSUE THREAD

**Issue by houd1ni** [manishsaraan/email-validator#73]
Hi, @manishsaraan ! Do you still maintain the lib? I see, there're a lot of old open issues.
If you just have no time, would you like to share the access to issues and PRs and possibly npm publishing ?
I don't want to create YeT AnOThEr email validation lib, but rather be sure that some of the popular is in my production.

**Comment by houd1ni** [comment]
Hi! Try this [akiliev@outlook.com](mailto:akiliev@outlook.com) please.

**Comment by manishsaraan** [comment]
Invited. please check your email
