### ISSUE TITLE
Why are email addresses containing dot in the username part considered invalid?

### ISSUE THREAD

**Issue by moaazbhnas228** [manishsaraan/email-validator#77]
`EmailValidator` considers an email in this format `test.test@gmail.com` invalid. Why? And is there a way to make it accept this format?

**Comment by houd1ni** [comment]
Hi. Just rechecked - it does support this email, and considers it valid.
Try just importing `const validator = require('email-validator'); console.log(validator.validate('test.test@gmail.com'))`.
